Resolve installation error.
install_github command fails to install the package due to the following error:

Error: Failed to install 'gumshoe' from GitHub:
  Missing commas separating Remotes: 'sinhrks/ggfortify
	hadley/dplyr
	pachterlab/sleuth'

Added commas between the remotes. Added tibble and biomRt into the description file. Added myself as a contributor in case an error comes up in the future related to my functions.